services:
  doxygen:
    build: .
    environment:
      - GIT_REPO=https://github.com/RIOT-OS/RIOT
      - API_KEY=rkzc7ez3jm078myn79csa0k3t45velcl
    ports:
      - "8004:4244"
    container_name: doxybuilder-${COMPOSE_PROJECT_NAME}
    restart: always
