#!/bin/sh
printstd()
{
	echo "[gen-doxygen] $1" > /dev/stdout
}
clean()
{
	if [ -f /var/run/hook/hook.lock ]; then
		printstd "Lock on hook released"
		rm /var/run/hook/hook.lock
	fi
	exit
}
printstd "gen-doxygen starting $(date)"

#We clone the repo and we generate the doxygen documentation.
REPO=$(cat /var/data/config/git_repo)
cd /var/data/repo/
git config --global --add safe.directory /var/data/repo

#Is the repo https?
if [ ! -d /var/data/repo/.git ]; then
    git clone $REPO /var/data/repo
	if [ ! $(ls -A /var/data/repo/) ]; then
		printstd "ERROR: Repo is empty abording."
		clean
	fi
else
	printstd "Pulling repo $REPO"
	git pull origin master
fi

cd /var/data/repo
make doc

#We update the documentation directory
mkdir -p /var/data/html/generated/
rm -rf /var/data/html/generated/*
cp -R /var/data/repo/doc/doxygen/html/* /var/data/html/

#We check if the lock file is still present
clean
